### ISSUE TITLE
User interface/experience: application will appear very unresponsive until / if user manages to find the 'double-click' setting

### ISSUE THREAD

**Issue by ghost** [dave-theunsub/clamtk#100]
It is not intuitive that icons need *double*-clicking. I inferred that the application had serious problems until I remembered, from years ago, that one has to double-click. There is a setting to change that behaviour but many users will not find it (and there's some testimony to that latter, from one of your own developers, in this report: #73).

Please change this default requirement to double-click or at least make its existence more evident.

clamtk 5-25-1
Linux 4.17.4-041704-generic x86_64 x86_64
Linux Mint 19

**Comment by dave-theunsub** [comment]
Hi,

Thanks for the feedback!  I think I initially went with double-click because that was the default. Later I figured out how to change it to single-click.  Then I had a decision to make: completely remove double-click or keep it and single-click. I was thinking more options meant better and wouldn't be disruptive to those used to double-clicking, but quickly found out otherwise. :)

Anyway, I'm rebuilding my system which died and will get back on this.  It shouldn't be too difficult or time-consuming.

respectfully
Dave M

**Comment by dave-theunsub** [comment]
Hi, this should be fixed now. Please open a new issue if you have further questions.
