### ISSUE TITLE
Clam Issue

### ISSUE THREAD

**Issue by rcmmulti** [dave-theunsub/clamtk#42]
I'm just trying to let Clam know that it found this (PUA.Win.Exploit.CVE_2012_0110) on my
system Ubuntu 14.04LTS but I can not delete or quarantine it! Also 36 other virus software's see it as
not a virus. That's one (Clam) says it is and 36 others saying it is not a virus.
Only you can set things right.!
Thanks
RM

**Comment by dave-theunsub** [comment]
Hi RM,

A PUA is "just" a potentially unwanted application.  It can mean any number of things, but they are not necessarily bad.  Because it can be so misleading, I actually recommend disabling that option with ClamTk.

You cannot delete it because you likely do not have the permissions to do so.  I would recommend you upload it to ClamAV maintainers to report it as a false positive, but they do not accept PUAs - see here: http://cgi.clamav.net/sendvirus.cgi

Also, you can whitelist specific directories, which may be handy in this situation.

I am curious - what kind of file is it, anyway?

Thanks,
Dave M

**Comment by dave-theunsub** [comment]
On second thought, here's a newer ClamAV page where you probably can submit a false positive:

http://www.clamav.net/report/report-fp.html

Thanks,
Dave M
