### ISSUE TITLE
Problem with KDE

### ISSUE THREAD

**Issue by Achimd1** [dave-theunsub/clamtk#44]
The clamtk version 5.1x does not work with with Linux Mint KDE 64Bit; if you start clamtk it runs in a loop

for a while, then it closed by themselve, the gui does not open.

**Comment by dave-theunsub** [comment]
Hi,

Please try the following:

https://code.google.com/p/clamtk/wiki/UpdateNotesWarning

Specifically:
----------
I'm using Kubuntu (or KDE), and ClamTk? won't start. There is an error message "Icon 'gtk-new' not present"

That's because unlike Ubuntu, Kubuntu does not have all the "built-in" gnome icons. This should fix the problem:

sudo apt-get install gnome-icon-theme-full
----------

So, please try the sudo command above.  See if that helps - let me know if you have further questions.

respectfully
Dave M

**Comment by Achimd1** [comment]
Hi Dave, thanks a lot, it still works for me! Greetings from Cologne, Germany, AchimDave M <notifications@github.com> hat am 29. April 2015 um 14:24 geschrieben:Hi,Please try the following:https://code.google.com/p/clamtk/wiki/UpdateNotesWarningSpecifically:I'm using Kubuntu (or KDE), and ClamTk? won't start. There is an error message "Icon 'gtk-new' not present"That's because unlike Ubuntu, Kubuntu does not have all the "built-in" gnome icons. This should fix the problem:sudo apt-get install gnome-icon-theme-fullSo, please try the sudo command above. See if that helps - let me know if you have further questions.respectfully Dave M—Reply to this email directly or view it on GitHub.

**Comment by dave-theunsub** [comment]
Closing based on https://github.com/dave-theunsub/clamtk/issues/44#issuecomment-97758151
