### ISSUE TITLE
GUI Font in Linux Mint 17.2, Cinnamon 2.6.13 - 64bit

### ISSUE THREAD

**Issue by Triplethread** [dave-theunsub/clamtk#52]
The GUI font of ClamTK 5.2 is not the system font but monospaced. Maybe it is better to get the system font or to add a choice in preferences?
![clamtk-5 2](https://cloud.githubusercontent.com/assets/536846/11615180/5244a338-9c5a-11e5-9345-e555ba8cdd74.jpg)

**Comment by dave-theunsub** [comment]
Sorry for the delay - this should already be taken care of in ClamTk 6, and I'll see if it's feasible to do so in the 5.xx series.

**Comment by Triplethread** [comment]
Wow, ClamTK6 - cant wait for!
Thank you for working at.

**Comment by haevalencia** [comment]
@dave-theunsub Is it possible to test the version 6? 
I have some problems processor usage that only occur using clamtk in fedora XFCE spin, and not using clamav in console, but I think would not be useful to make a report if it is developing a new version.

**Comment by dave-theunsub** [comment]
@haevalencia - Version 6 is *kind of* ready, but I doubt you will see any relevant changes.  In fact, it might be *more* processor intensive than the 5.xx series.  Can you provide more details about the issues you're having?  Maybe that is the better way to go for now.

Thanks,
Dave M

**Comment by AXDOOMER** [comment]
@dave-theunsub Cool. I'd like to see a screenshot of version 6. Why are you doing a new user interface? I really liked version 4 and I don't understand why it was changed.

**Comment by dave-theunsub** [comment]
Well, that's a long story, but you have a good question.  I'll just assume you mean version 5 instead of version 4.  Gtk2 is deprecated, so we'll have to move to Gtk3.  So that's one reason - the graphics library has to be upgraded.  We were supposed to do that for the 5.xx series, but most Linux distributions weren't ready for Gtk3.  In light of that, with about two days left until the 5.xx release, I rewrote the entire thing to use Gtk2 but couldn't get it to look the way I wanted, so I made it look like an XFCE app (my favorite window manager).  Frankly, I hate it (the 5.xx series).

Anyway, that's the short of it.  If there are things you'd like to see or have removed, please either email me or open a bug report with your suggestions.

respectfully
Dave M

**Comment by Pastim** [comment]
Can I try version 6 on ubuntu 16.04 or not?  You have commented that libgtk3-perl on ubuntu is too old (it's 0.026-1 on my system). 

I assumed I didn't have to install anything else, just run clamtk, but now I think I may need to install modules using CPAN?  If so, how?

Having cloned calmtk-gtk3, running clamtk gives the error below, which implies to me that I need to do something more to install it.

The error message is:

Can't locate ClamTk/ApplicationSettings.pm in @INC (you may need to install the ClamTk::ApplicationSettings module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.22.1 /usr/local/share/perl/5.22.1 /usr/lib/x86_64-linux-gnu/perl5/5.22 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.22 /usr/share/perl/5.22 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base .) at /home/crusty/Programs/clamtk-gtk3/clamtk line 26.
BEGIN failed--compilation aborted at /home/crusty/Programs/clamtk-gtk3/clamtk line 26.

**Comment by AXDOOMER** [comment]
@dave-theunsub Thank you for taking the time to answer. I liked the previous GUI because the scan was done inside the main window, so you didn't have two windows opened while scanning. I prefer apps that have less windows because it gets messy fast on the desktop and it looks cleaner, but I understand why you did it like that for this version. You have no choice if you want to navigate inside the program while there's a scan. A good example of what I'm talking about is Skype on Linux vs Skype on Windows. On Windows, everything is in one window and there are subdivisions. If you move the window, everything follows. On Linux, Skype can have three windows opened at the same time. Every time you want to move it, you have to move the three windows, because it's one program and it logic to keep the grouped together.

**Comment by Pastim** [comment]
Apologies for my previous post - I hadn't read enough of your instructions (from http://clamtk.sourceforge.net/help/install-clamtk.html). 

Suffice to say that I have clamtk 6.0 running on ubuntu 16.04 (using libgtk3-perl 0.026-1) and it seems fine thus far (I don't see any tips, and not sure where to copy them to, but not an issue for me).

Thanks - a much nicer interface than 5.20.

**Comment by AXDOOMER** [comment]
@Pastim May you post a screenshot please?

**Comment by Pastim** [comment]
![screenshot from 2016-08-03 06-58-37](https://cloud.githubusercontent.com/assets/1884726/17355346/d5810480-5947-11e6-9ac8-98b40b9d22a2.png)

**Comment by dave-theunsub** [comment]
This should be fixed in 5.21.  Please open a new one if we need to do more work on it.

Thanks,
Dave M
