### ISSUE TITLE
No way to see the scan results

### ISSUE THREAD

**Issue by Michal-Mikolas** [dave-theunsub/clamtk#99]
Hello,  
I downloaded ClamTK and scan my home directory. The result screen looks like this:  

![screenshot_18-06-26_09-12-07](https://user-images.githubusercontent.com/900316/41895253-cd8eca7c-7921-11e8-9e1a-47906cc94797.png)

But I'm not able to see what the threats are. So I can not delete them! 

I've also tried to see the scan history. But it's empty: 

![screenshot_18-06-26_09-14-05](https://user-images.githubusercontent.com/900316/41895334-1237d6b4-7922-11e8-9b22-bada4afaaf52.png)

--
Linux Mint 18.1 64bit, ClamtTK 5.25

**Comment by ttsrg** [comment]
Hello. Me too have such trouble in ubuntu 18.04
http://joxi.ru/V2VNVypcxKWol2  And I don't know why I don't see that "result window"?

**Comment by ttsrg** [comment]
![image](https://user-images.githubusercontent.com/39533021/42515966-ae97b648-8465-11e8-9381-d9735cd6c9b0.png)

**Comment by Achaean** [comment]
Same problem here (on Devuan ASCII x64 KDE), with ClamTk v.5.26.

**Comment by dave-theunsub** [comment]
Hi,

Thanks for reporting the issues. I can't duplicate it on my current system, but will have better access this weekend.  Please give me a few days to check it out.

Thanks,

Dave M

**Comment by dave-theunsub** [comment]
Ok, I finally got 18.04 installed and patched up.

So far, the only thing I can duplicate is the "canberra-gtk-module" statement, which is solved by installing libcanberra-gtk-module as you've done.

Since the Perl module Encode is complaining, can you tell me what is the result of typing this in a terminal window?

`echo $LANG`

You should see something like

`en_US.UTF-8`

Thanks,
Dave M

**Comment by Achaean** [comment]
Personally, I'm using Greek language.
el_GR.UTF-8.

**Comment by dave-theunsub** [comment]
@Achaean , are you seeing anything different than the above (if you start it from the commandline "clamtk")?

**Comment by Achaean** [comment]
No. :-(

**Comment by gdzi** [comment]
So, how can I see scan results, are there a solution that I did not see. Sorry 3 month only in linux, great so far, but such hicaps irritate me a little.

**Comment by Achaean** [comment]
@gdzi:
Why don't use ClamAv from console, until this issue get fixed?
It's (more or less) easy and straightforward.

For providing a bit more personalized instructions, please tell me:
1) Which one distribution you use?
2) Are you using ClamAv on a daily basis, or in a while?

**Comment by dave-theunsub** [comment]
@gdzi Can you try this (if you haven't already):

Please open a terminal window and type "clamtk" (no quotes). Then run a quick scan. Sometimes there are error messages that pop up in the terminal window; if so, please send them as they might help us figure this out.

There has to be a reason nothing is showing up...

**Comment by gdzi** [comment]
![screenshot_20181228_180229](https://user-images.githubusercontent.com/38335350/50520396-24999b80-0ad1-11e9-8178-ac73be195918.png)
*** unhandled exception in callback:
***   Wide character at /usr/lib/x86_64-linux-gnu/perl/5.26/Encode.pm line 212.
***  ignoring at /usr/share/perl5/ClamTk/GUI.pm line 145.

**Comment by Achaean** [comment]
Kubuntu? Great!
Lets try:

1) You need to edit (as root) the text config file /etc/clamav/freshclam.conf (that means the freshclam.conf file who lives at the /etc/clamav/ directory).
Give from Konsole "kdesu kate" (without quotes).
If Kubuntu throws an error (because it don't likes the root account), try "kdesudo kate" (means you with root rights).

Open the /etc/clamav/freshclam.conf file.

* If you prefer KWrite, Nano or some other text editor instead of Kate, no problem. Use your preferred one.
** You can also try something like "kdesu kate  /etc/clamav/freshclam.conf" (instead of opening the file from inside Kate), if you prefer it.

2) Now that you opened it, you can edit it,
Change:
a) Checks 4 (or a similar number) -> Checks 0 (so you can disable the autoupdate).
Leave it intact, if you prefer autoupdate.
b) There's a line who starts with "NotifyClamd..."
Comment it out (or delete the entire line), in order to avoid a silly warning message.
If you left Clamav autoupdate, don't bother with this line.

3) If you disabled autoupdate, every time you want to update, run (as root) "freshclam".
Give "su -", in order to get to a root konsole and then run "freshclam".
If Kubuntu denies the root konsole try: "sudo freshclam".
If you left the autoupdate, don't bother with it either.

4) Now the important stuff. You have a directory with the files in question (you want to check) and you just want to check them.
Point the konsole to that directory and run: "clamscan -r --bell".
* -r stands for recursive. It scan the current directory and all subdirectories.
If you don't want the subdirectories scan, omit it.
** -bell rings the system bell, in case infection(s) found. If you don't want to hear the ding sound, omit it too.

Note: Do you know how to point Konsole to the desired directory?
At Dolphin go to Settings -> Configure Dolphin -> Services -> and enable "open terminal here" or "run in Konsole".

Problems? Questions?

**Comment by gdzi** [comment]
@Achaean Yes, yes, very detailed, most likely very useful. Do not think that I'm rude, but I have a small question: How is this fix the result screen problem in clamTK?

**Comment by dave-theunsub** [comment]
@gdzi Thanks for answering! This is really weird since I don't remember changing anything that would prompt that.

Anyway, if you wouldn't mind, would you please post what the result of "echo $LANG" is?  Thanks again

**Comment by gdzi** [comment]
`echo $LANG`
ru_RU.UTF-8
`locale`
LANG=ru_RU.UTF-8
LANGUAGE=en_US
LC_CTYPE="ru_RU.UTF-8"
LC_NUMERIC="ru_RU.UTF-8"
LC_TIME="ru_RU.UTF-8"
LC_COLLATE="ru_RU.UTF-8"
LC_MONETARY="ru_RU.UTF-8"
LC_MESSAGES="ru_RU.UTF-8"
LC_PAPER="ru_RU.UTF-8"
LC_NAME="ru_RU.UTF-8"
LC_ADDRESS="ru_RU.UTF-8"
LC_TELEPHONE="ru_RU.UTF-8"
LC_MEASUREMENT="ru_RU.UTF-8"
LC_IDENTIFICATION="ru_RU.UTF-8"
LC_ALL=

Strang to see a languch may affect on GUI, a really strange bug indeed. And yes I'm Russian, but for many programs I use English, it is better to learn language this way.

**Comment by Achaean** [comment]
> @Achaean Yes, yes, very detailed, most likely very useful. Do not think that I'm rude, but I have a small question: How is this fix the result screen problem in clamTK?

It wont! :-)
(As I said earlier), it's only a temporary solution, until this bug ironed out.

**Comment by dave-theunsub** [comment]
Closing for now. Please open a new issue if you have further questions.

**Comment by pythogoras** [comment]
file clamtk:
42| setlocale( LC_ALL, ' ' ); => setlocale( LC_ALL, 'en_US.UTF-8' );
ubuntu:
usr/bin/clamtk
42| setlocale( LC_ALL, ' ' ); => setlocale( LC_ALL, 'en_US.UTF-8' );

**Comment by pythogoras** [comment]
https://music.youtube.com/watch?v=B9uNTT5WBSQ&list=PLAHNHamfBpdEg3Wj8lmeZxtCGeKH287VH

**Comment by dave-theunsub** [comment]
Fixed in 6.09.

Thank you to everyone who reported!

respectfully,  
Dave M
